name = "gdgjp-accounts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[vars]
APP_URL = "https://accounts.gdgs.jp"
CLERK_PUBLISHABLE_KEY = "pk_test_ZWFzeS1ncmFja2xlLTkyLmNsZXJrLmFjY291bnRzLmRldiQ"

[assets]
binding = "ASSETS"
directory = "./build/client"

# [[d1_databases]]
# binding = "DB"
# database_name = "gdgjp-accounts"
# database_id = "TODO"

# [[kv_namespaces]]
# binding = "AUTH_KV"
# id = "TODO"
