name = "gdgjp-accounts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[alias]
"virtual:react-router/server-build" = "./build/server/index.js"

[vars]
APP_URL = "https://account.gdgs.jp"
GOOGLE_CLIENT_ID = "144403252439-hnm3r310icb0l9o6v5hqrurf6h2faidi.apps.googleusercontent.com"
TINYURL_CLIENT_ID = "tinyurl"
TINYURL_REDIRECT_URLS = "https://url.gdgs.jp/api/auth/oauth2/callback/gdgjp"
WIKI_CLIENT_ID = "wiki"
WIKI_REDIRECT_URLS = "https://wiki.gdgs.jp/api/auth/oauth2/callback/gdgjp"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-accounts"
database_id = "c97d5ddc-231a-4b1a-af2a-fe753876811d"
migrations_dir = "./migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
