name = "gdgjp-tinyurl"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[alias]
"virtual:react-router/server-build" = "./build/server/index.js"

[vars]
APP_URL = "https://url.gdgs.jp"
ACCOUNTS_URL = "https://accounts.gdgs.jp"
SHORT_URL_BASE = "https://gdgs.jp"
CLERK_PUBLISHABLE_KEY = "pk_test_ZWFzeS1ncmFja2xlLTkyLmNsZXJrLmFjY291bnRzLmRldiQ"
CLERK_IS_SATELLITE = "true"
CLERK_DOMAIN = "url.gdgs.jp"
CLERK_SIGN_IN_URL = "https://accounts.gdgs.jp/signin"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-tinyurl"
database_id = "bf0cefab-83d5-48c8-a2a7-7842e9890c46"
migrations_dir = "./migrations"

[[analytics_engine_datasets]]
binding = "CLICKS_AE"
dataset = "tinyurl_clicks"

[[routes]]
pattern = "url.gdgs.jp/*"
zone_name = "gdgs.jp"

[[routes]]
pattern = "gdgs.jp/*"
zone_name = "gdgs.jp"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
