name = "gdgjp-tinyurl"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[alias]
"virtual:react-router/server-build" = "./build/server/index.js"

[vars]
APP_URL = "https://url.gdgs.jp"
ACCOUNTS_URL = "https://account.gdgs.jp"
SHORT_URL_BASE = "https://gdgs.jp"
IDP_URL = "https://account.gdgs.jp"
IDP_CLIENT_ID = "tinyurl"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-tinyurl"
database_id = "bf0cefab-83d5-48c8-a2a7-7842e9890c46"
migrations_dir = "./migrations"

[[analytics_engine_datasets]]
binding = "CLICKS_AE"
dataset = "tinyurl_clicks"

[[routes]]
pattern = "url.gdgs.jp/*"
zone_name = "gdgs.jp"

[[routes]]
pattern = "gdgs.jp/*"
zone_name = "gdgs.jp"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
