name = "gdgjp-wiki"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[vars]
APP_URL = "https://wiki.gdgs.jp"
ACCOUNTS_URL = "https://accounts.gdgs.jp"
IDP_URL = "https://accounts.gdgs.jp"
IDP_CLIENT_ID = "wiki"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gdgjp-wiki"
database_id = ""
migrations_dir = "./migrations"
