-- Schema dump for @gdgjp/roster
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE application_skills (
  application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  role_id        TEXT NOT NULL REFERENCES roles(id),
  level          TEXT NOT NULL DEFAULT 'new' CHECK (level IN ('lead','exp','new')),
  pref           INTEGER NOT NULL DEFAULT 2 CHECK (pref IN (1,2)),
  PRIMARY KEY (application_id, role_id)
);
CREATE TABLE applications (
  id           TEXT PRIMARY KEY,
  event_id     TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id      TEXT,                        -- NULL only for a proxy registration
  email        TEXT NOT NULL,
  name         TEXT NOT NULL,
  contact      TEXT,                        -- day-of contact method (optional)
  party        TEXT NOT NULL DEFAULT 'undecided'
                 CHECK (party IN ('yes','no','undecided')),
  note         TEXT,
  withdrawn    INTEGER NOT NULL DEFAULT 0,
  updated_by   TEXT NOT NULL DEFAULT 'self' CHECK (updated_by IN ('self','owner')),
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE TABLE assignments (
  event_id       TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  time_slot_id   TEXT NOT NULL REFERENCES time_slots(id) ON DELETE CASCADE,
  track_id       TEXT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  role_id        TEXT NOT NULL REFERENCES roles(id),
  locked         INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (application_id, time_slot_id)
);
CREATE TABLE availabilities (
  application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  time_slot_id   TEXT NOT NULL REFERENCES time_slots(id) ON DELETE CASCADE,
  value          TEXT NOT NULL CHECK (value IN ('o','d','x')),
  PRIMARY KEY (application_id, time_slot_id)
);
CREATE TABLE demands (
  event_id     TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  time_slot_id TEXT NOT NULL REFERENCES time_slots(id) ON DELETE CASCADE,
  track_id     TEXT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  role_id      TEXT NOT NULL REFERENCES roles(id),
  min_count    INTEGER NOT NULL DEFAULT 0,
  ideal_count  INTEGER NOT NULL DEFAULT 0,
  lead_min     INTEGER NOT NULL DEFAULT 0,
  new_max      INTEGER NOT NULL DEFAULT 99,
  PRIMARY KEY (time_slot_id, track_id, role_id)
);
CREATE TABLE event_roles (
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  role_id  TEXT NOT NULL REFERENCES roles(id),
  PRIMARY KEY (event_id, role_id)
);
CREATE TABLE events (
  id                TEXT PRIMARY KEY,
  chapter_id        INTEGER NOT NULL,
  name              TEXT NOT NULL,
  date              TEXT NOT NULL,               -- YYYY-MM-DD
  start_time        TEXT NOT NULL CHECK (length(start_time) = 5),
  end_time          TEXT NOT NULL CHECK (length(end_time) = 5),
  step_min          INTEGER NOT NULL DEFAULT 60, -- 15 | 30 | 60
  tz                TEXT NOT NULL DEFAULT 'Asia/Tokyo',
  status            TEXT NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','open','closed','published','ended')),
  has_party         INTEGER NOT NULL DEFAULT 0,
  no_solo_newcomer  INTEGER NOT NULL DEFAULT 1,
  max_consecutive   INTEGER NOT NULL DEFAULT 4,
  seed              INTEGER NOT NULL,
  apply_token       TEXT NOT NULL UNIQUE,
  view_token        TEXT NOT NULL UNIQUE,
  created_by        TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  deleted_at        TEXT
);
CREATE TABLE oidc_session (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  issuer TEXT NOT NULL,
  subject TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  id_token TEXT NOT NULL,
  access_token_expires_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);
CREATE TABLE phases (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  from_time  TEXT NOT NULL,
  to_time    TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);
CREATE TABLE roles (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);
CREATE TABLE time_slots (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  idx        INTEGER NOT NULL,
  start_time TEXT NOT NULL,
  end_time   TEXT NOT NULL,
  phase_id   TEXT REFERENCES phases(id) ON DELETE SET NULL,
  UNIQUE (event_id, idx)
);
CREATE TABLE tracks (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  color      TEXT NOT NULL,
  shared     INTEGER NOT NULL DEFAULT 0,   -- the "全体" track
  sort_order INTEGER NOT NULL
);
CREATE TABLE "user" (
  id           TEXT PRIMARY KEY,
  email        TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  image        TEXT,
  is_admin     INTEGER NOT NULL DEFAULT 0,
  oidc_issuer  TEXT,
  oidc_subject TEXT,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE UNIQUE INDEX applications_event_email ON applications (event_id, email);
CREATE INDEX applications_event_idx ON applications (event_id);
CREATE UNIQUE INDEX applications_event_user ON applications (event_id, user_id)
  WHERE user_id IS NOT NULL;
CREATE INDEX assignments_event_idx ON assignments (event_id);
CREATE INDEX demands_event_idx ON demands (event_id);
CREATE INDEX events_chapter_idx ON events (chapter_id) WHERE deleted_at IS NULL;
CREATE INDEX oidc_session_user_idx ON oidc_session (user_id);
CREATE INDEX phases_event_idx ON phases (event_id);
CREATE INDEX time_slots_event_idx ON time_slots (event_id);
CREATE INDEX tracks_event_idx ON tracks (event_id);
CREATE UNIQUE INDEX user_oidc_identity
  ON "user" (oidc_issuer, oidc_subject)
  WHERE oidc_issuer IS NOT NULL AND oidc_subject IS NOT NULL;
